# Generated by Django 3.1.7 on 2021-02-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=150)),
                ('date_of_completion', models.DateField(blank=True, default=' ', null=True)),
            ],
            options={
                'verbose_name': 'Список задач',
                'verbose_name_plural': 'Список задачи',
                'db_table': 'To-Do list',
            },
        ),
    ]
