# Generated by Django 3.1.7 on 2021-03-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_list_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='describe',
            field=models.TextField(max_length=150),
        ),
    ]
