# Generated by Django 3.1.7 on 2021-03-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210301_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date_of_completion',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterModelTable(
            name='list',
            table='list',
        ),
    ]
